---

is_debug: true
listen:
  type: port
  host: 0.0.0.0
  port: 1234
storage:
  host: 0.0.0.0
  port: 5432
  database: postgres
  username: postgres
  password: postgres
#mongodb:
#  host: 0.0.0.0
#  port: 27017
#  database: service
#  auth: admin
#  username: admin
#  password: admin
#  collection: users
