###
//All products from table
GET http://127.0.0.1:1234/products/
Content-Type: application/json

###
//Create new product in table
POST http://127.0.0.1:1234/products/
Content-Type: application/json

{
  "name": "картошка",
  "price": 10,
  "count": 45,
  "date": "2024-03-12"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status == 201, "Response status is not 201")
    })
%}

###
// certain product by id
GET http://127.0.0.1:1234/products/1
Content-Type: application/json

###
PUT http://127.0.0.1:1234/products
Content-Type: application/json

{
  "id": 10,
  "name": "лук",
  "price": 13,
  "count": 23,
  "date": "2024-02-24"
}


> {%
client.test("Request executed successfully", function () {
    client.assert(response.status == 201, "Response status is not 201")
})
 %}

###
GET http://127.0.0.1:1234/report
Content-Type: application/json

###
PATCH http://127.0.0.1:1234/products/1
Content-Type: application/json

{}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status == 204, "Response status is not 204")
    })
%}

###
DELETE http://127.0.0.1:1234/products/1
Content-Type: application/json

{}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status == 204, "Response status is not 204")
    })
%}
