
--добавилось поле data
CREATE TABLE public.product (
                                id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                name VARCHAR(100) NOT NULL,
                                price integer NOT NULL,
                                count integer NOT NULL,
                                date date
);

INSERT INTO product (name, price, count) values ('банан', 30, 2, "2024-07-24");
INSERT INTO product (name, price, count) values ('яблоко', 20, 6, "2024-07-01");
INSERT INTO product (name, price, count) values ('мандарины', 45, 4, "2024-07-05");
INSERT INTO product (name, price, count) values ('виноград', 60, 1, "2024-07-10");