POST http://0.0.0.0:10000/products
Content-Type: application/json

{}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status == 201, "Response status is not 201")
    })
%}

###
PUT http://0.0.0.0:10000/products/1
Content-Type: application/json

{}

> {%
client.test("Request executed successfully", function () {
    client.assert(response.status == 201, "Response status is not 201")
})
 %}


###
PATCH http://0.0.0.0:10000/products/1
Content-Type: application/json

{}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status == 204, "Response status is not 204")
    })
%}

###
DELETE http://0.0.0.0:10000/products/1
Content-Type: application/json

{}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status == 204, "Response status is not 204")
    })
%}
