###
//All products from table
GET http://127.0.0.1:1234/products/
Content-Type: application/json



###
//Create new product in table
POST http://127.0.0.1:1234/products/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV4YW1wbGVVc2VyIiwiZXhwIjoxNzIwMjk1NjgzfQ.KR69LhC_I272U4afYSClofrU40JJyiACsXEUKu-iQVo

{
  "name": "оливки",
  "price": 113,
  "count": 2,
  "date": "2024-01-03"
}

###
// certain product by id
GET http://127.0.0.1:1234/products/10
Content-Type: application/json

###
//update product INVALID JWT TOCKEN
PUT http://127.0.0.1:1234/products
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV4YW1wbGVVc2VyIiwiZXhwIjoxNzIwMjgwNTE5fQ.JLplBfUzTE6NP-8vST5QlhqRZftCfzWqoi2Ftn3wMsI

{
  "id": 10,
  "name": "желуди",
  "price": 24,
  "count": 63
}

###
//create report INVALID JWT TOCKEN
GET http://127.0.0.1:1234/report
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNzIwMzM4NzM4fQ.kVxkLy0JmLQCwLxN9MUnYsZAclhfz-MBxCxip93F4xM

###
//Create JWT token
GET http://127.0.0.1:1234/auth
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
POST http://127.0.0.1:1234/auth
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###
//Delete product
DELETE http://127.0.0.1:1234/delete/13
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImV4YW1wbGVVc2VyIiwiZXhwIjoxNzIwMjk1NjgzfQ.KR69LhC_I272U4afYSClofrU40JJyiACsXEUKu-iQVo
Content-Type: application/json

